trigger_gas_update:
  description: "Trigger gas meter calculation logic."
  fields:
    datetime:
      description: "The timestamp for the gas meter reading (format: YYYY-MM-DD HH:MM)."
      example: "2025-02-12 15:51"
    consumed_gas:
      description: "The gas meter reading in cubic meters with a dot as a delimiter."
      example: 4447.816

read_gas_actualdata_file:
  description: "Read gas meter file."

debug_history_stats_sensor:
  description: "Debuging function which allows to discover the valid params for HistoryStatsUpdateCoordinator (from homeassistant.components.history_stats.coordinator)."
